// dpnetshim - transparent DirectPlay8 capture shim (Phase 0).
//
// Two Worlds creates its DirectPlay8 objects via CoCreateInstance, so
// registering this DLL for the DirectPlay8 CLSIDs under the per-user
// WOW6432Node branch puts it in front of the real dpnet.dll without
// touching any system file or needing admin rights.
//
// This build stays fully transparent: every IDirectPlay8Peer method is a
// real C++ forwarder (vtable generated by the compiler from the canonical
// header, so slot order is correct by construction - the previous generic
// asm thunk crashed because it never swapped the this pointer). Each call
// is logged, and Initialize wraps the game's message handler so the real
// DirectPlay message sequence is captured too. The log is the ground
// truth for what the replacement must implement.
//
// Header: Wine dplay8.h/dpaddr.h (LGPL) - fine for this local capture
// tool; the distributed replacement will use a permissive header.

#define WIN32_LEAN_AND_MEAN
#define INITGUID
#include <windows.h>
#include <dplay8.h>
#include <dpaddr.h>
#include <stdio.h>

static HMODULE g_realDpnet = NULL;
static LONG g_factoryRefs = 0;
static CRITICAL_SECTION g_logLock;
static bool g_logReady = false;

#define LOGPATH "C:\\Users\\marco\\Desktop\\twMP\\dpnetshim.log"

static void LogInit()
{
    if (!g_logReady) { InitializeCriticalSection(&g_logLock); g_logReady = true; }
}

static void Log(const char* fmt, ...)
{
    if (!g_logReady) return;
    EnterCriticalSection(&g_logLock);
    FILE* f = NULL;
    if (fopen_s(&f, LOGPATH, "a") == 0 && f) {
        SYSTEMTIME st; GetLocalTime(&st);
        fprintf(f, "[%02d:%02d:%02d.%03d] ", st.wHour, st.wMinute,
                st.wSecond, st.wMilliseconds);
        va_list a; va_start(a, fmt); vfprintf(f, fmt, a); va_end(a);
        fprintf(f, "\n");
        fclose(f);
    }
    LeaveCriticalSection(&g_logLock);
}

// -- DPN_MSGID_* names, for a readable message trace -------------------

static const char* MsgName(DWORD id)
{
    switch (id) {
    case DPN_MSGID_CREATE_PLAYER:        return "CREATE_PLAYER";
    case DPN_MSGID_DESTROY_PLAYER:       return "DESTROY_PLAYER";
    case DPN_MSGID_ENUM_HOSTS_QUERY:     return "ENUM_HOSTS_QUERY";
    case DPN_MSGID_ENUM_HOSTS_RESPONSE:  return "ENUM_HOSTS_RESPONSE";
    case DPN_MSGID_INDICATE_CONNECT:     return "INDICATE_CONNECT";
    case DPN_MSGID_INDICATED_CONNECT_ABORTED: return "INDICATED_CONNECT_ABORTED";
    case DPN_MSGID_CONNECT_COMPLETE:     return "CONNECT_COMPLETE";
    case DPN_MSGID_RECEIVE:              return "RECEIVE";
    case DPN_MSGID_SEND_COMPLETE:        return "SEND_COMPLETE";
    case DPN_MSGID_TERMINATE_SESSION:    return "TERMINATE_SESSION";
    case DPN_MSGID_ADD_PLAYER_TO_GROUP:  return "ADD_PLAYER_TO_GROUP";
    case DPN_MSGID_REMOVE_PLAYER_FROM_GROUP: return "REMOVE_PLAYER_FROM_GROUP";
    case DPN_MSGID_CREATE_GROUP:         return "CREATE_GROUP";
    case DPN_MSGID_DESTROY_GROUP:        return "DESTROY_GROUP";
    case DPN_MSGID_APPLICATION_DESC:     return "APPLICATION_DESC";
    case DPN_MSGID_HOST_MIGRATE:         return "HOST_MIGRATE";
    case DPN_MSGID_RETURN_BUFFER:        return "RETURN_BUFFER";
    case DPN_MSGID_PEER_INFO:            return "PEER_INFO";
    case DPN_MSGID_ASYNC_OP_COMPLETE:    return "ASYNC_OP_COMPLETE";
    default:                             return "MSGID_?";
    }
}

// -- transparent peer wrapper -----------------------------------------

class PeerShim : public IDirectPlay8Peer {
public:
    explicit PeerShim(IDirectPlay8Peer* real)
        : m_ref(1), m_real(real), m_gameHandler(NULL), m_gameContext(NULL) {}

    // IUnknown
    STDMETHODIMP QueryInterface(REFIID riid, void** ppv) override {
        if (IsEqualIID(riid, IID_IUnknown) ||
            IsEqualIID(riid, IID_IDirectPlay8Peer)) {
            *ppv = static_cast<IDirectPlay8Peer*>(this);
            AddRef();
            return S_OK;
        }
        return m_real->QueryInterface(riid, ppv);
    }
    STDMETHODIMP_(ULONG) AddRef() override { return InterlockedIncrement(&m_ref); }
    STDMETHODIMP_(ULONG) Release() override {
        LONG r = InterlockedDecrement(&m_ref);
        if (r == 0) { m_real->Release(); delete this; }
        return r;
    }

    // Initialize wraps the game's message handler so we see the message
    // stream. We pass ourselves as the DirectPlay user context and a
    // static thunk as the handler.
    STDMETHODIMP Initialize(PVOID pvUserContext, PFNDPNMESSAGEHANDLER pfn,
                            DWORD dwFlags) override {
        Log("CALL Peer::Initialize (flags=0x%lX)", dwFlags);
        m_gameHandler = pfn;
        m_gameContext = pvUserContext;
        return m_real->Initialize(this, &PeerShim::MsgThunk, dwFlags);
    }

    static HRESULT WINAPI MsgThunk(PVOID ctx, DWORD msgid, PVOID msg) {
        PeerShim* self = static_cast<PeerShim*>(ctx);
        Log("  MSG %s", MsgName(msgid));
        HRESULT hr = self->m_gameHandler(self->m_gameContext, msgid, msg);
        if (hr != S_OK)
            Log("  MSG %s -> game returned 0x%08lX", MsgName(msgid), hr);
        return hr;
    }

#include "peer_forwarders.inc"

private:
    LONG m_ref;
    IDirectPlay8Peer* m_real;
    PFNDPNMESSAGEHANDLER m_gameHandler;
    PVOID m_gameContext;
};

// -- class factory -----------------------------------------------------

typedef HRESULT (WINAPI *PFN_DllGetClassObject)(REFCLSID, REFIID, LPVOID*);

class ShimFactory : public IClassFactory {
public:
    ShimFactory(IClassFactory* real) : m_ref(1), m_real(real) {}

    STDMETHODIMP QueryInterface(REFIID riid, void** ppv) override {
        if (IsEqualIID(riid, IID_IUnknown) || IsEqualIID(riid, IID_IClassFactory)) {
            *ppv = static_cast<IClassFactory*>(this); AddRef(); return S_OK;
        }
        return m_real->QueryInterface(riid, ppv);
    }
    STDMETHODIMP_(ULONG) AddRef() override { return InterlockedIncrement(&m_ref); }
    STDMETHODIMP_(ULONG) Release() override {
        LONG r = InterlockedDecrement(&m_ref);
        if (r == 0) { m_real->Release(); InterlockedDecrement(&g_factoryRefs); delete this; }
        return r;
    }
    STDMETHODIMP CreateInstance(IUnknown* outer, REFIID riid, void** ppv) override {
        Log("CreateInstance riid={%08lX-...}", ((const GUID&)riid).Data1);
        HRESULT hr = m_real->CreateInstance(outer, riid, ppv);
        if (SUCCEEDED(hr) && ppv && *ppv &&
            IsEqualIID(riid, IID_IDirectPlay8Peer)) {
            *ppv = new PeerShim((IDirectPlay8Peer*)*ppv);
            Log("  wrapped DirectPlay8Peer");
        }
        return hr;
    }
    STDMETHODIMP LockServer(BOOL lock) override { return m_real->LockServer(lock); }

private:
    LONG m_ref;
    IClassFactory* m_real;
};

// -- exports -----------------------------------------------------------

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
    LogInit();
    Log("DllGetClassObject clsid={%08lX-...} riid={%08lX-...}",
        rclsid.Data1, ((const GUID&)riid).Data1);

    if (!g_realDpnet) {
        char path[MAX_PATH];
        GetSystemDirectoryA(path, MAX_PATH);   // SysWOW64 for a 32-bit process
        strcat_s(path, MAX_PATH, "\\dpnet.dll");
        g_realDpnet = LoadLibraryA(path);
        Log("  loaded real dpnet: %s -> %p", path, g_realDpnet);
    }
    if (!g_realDpnet) return CLASS_E_CLASSNOTAVAILABLE;

    PFN_DllGetClassObject real = (PFN_DllGetClassObject)
        GetProcAddress(g_realDpnet, "DllGetClassObject");
    if (!real) return CLASS_E_CLASSNOTAVAILABLE;

    HRESULT hr = real(rclsid, riid, ppv);
    if (SUCCEEDED(hr) && IsEqualIID(riid, IID_IClassFactory) && ppv && *ppv) {
        // Only wrap the Peer factory; other classes pass through untouched.
        if (IsEqualGUID(rclsid, CLSID_DirectPlay8Peer)) {
            *ppv = new ShimFactory((IClassFactory*)*ppv);
            InterlockedIncrement(&g_factoryRefs);
            Log("  wrapped Peer class factory");
        }
    }
    return hr;
}

STDAPI DllCanUnloadNow(void)
{
    return g_factoryRefs == 0 ? S_OK : S_FALSE;
}

BOOL WINAPI DllMain(HINSTANCE inst, DWORD reason, LPVOID)
{
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(inst);
        LogInit();
        Log("=== dpnetshim geladen (pid %lu) ===", GetCurrentProcessId());
    }
    return TRUE;
}
